config/routes.rb
CmsBeta2::Application.routes.draw do
  devise_for :users
  resources :pages, :system, :design
  devise_scope :user do
    get "home"   => "devise/sessions#new"
    get 'logout' => 'devise/sessions#destroy'
  end
  

   

  root :to => 'home#index'
end

app/models/layout.rb
class Layout < ActiveRecord::Base
  belongs_to :user
  belongs_to :pages
end

app/models/live.rb
class Live < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :user
end

app/models/pagetext.rb
class Pagetext < ActiveRecord::Base
end

app/models/psetting.rb
class Psetting < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pages
  has_many :layouts
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
require 'Menu'
class ApplicationController < ActionController::Base
  protect_from_forgery 
  helper_method :all
end

app/controllers/design_controller.rb
class DesignController < ApplicationController
  before_filter :authenticate_user!
  def index
    #@layout = Layout.find(:all)
    @layout = current_user.layouts.all

  end
  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	#before_filter :authenticate_user!
	def index
		if user_signed_in?
      redirect_to "/system"
    end
    else if request.post?
      redirect_to "/home"
    end
	end	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_filter :authenticate_user!

	def index
		@pageTree = current_user.pages.find(:all)
		@pageSubs = current_user.pages.where("subpage >= ?", 1)
	end
	def show
		@page     = Page.find(params[:id])	
		@pageTree = current_user.pages.where(:subpage != 0)
	end
	def edit
		@page     = Page.find(params[:id])	
		@pageTree = current_user.pages.all
	end	
	def update
		@page = current_user.pages.find(params[:id])
		respond_to do |format|
			if @page.update_attributes(params[:page])
				format.js
			end
		end
	end
	def create	
		@page = current_user.pages.new(params[:page])
		respond_to do |format|
			if @page.save
				format.html { redirect_to @page, notice: "Din sida har nu skapats" }
				#format.js -> If request is needed
			end
		end
	end
	def destroy
		@page = current_user.pages.find(params[:id])
		@page.destroy
		respond_to do |format|
			format.html {redirect_to pages_path, notice: "Sidan har nu raderats"}

		end

	end
end

app/controllers/system_controller.rb
class SystemController < ApplicationController
	before_filter :authenticate_user!
	def index
	  @dashoard  = Dashboard.new
	  @client_ip = request.remote_ip
	  @remote_ip = request.env["HTTP_X_FORWARDED_FOR"]
	  @my_ip     = request.env["HTTP_X_FORWARDED_FOR"] || request.remote_addr
  	  @ip_addr   = request.env['REMOTE_ADDR']
	end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
	before_filter :authenticate_user!
	def index
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	#before_filter :authenticate_user!
	def sign_in
	if request.post?
      redirect_to "/home"
    
	end	
	def logout
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def fetch_sign_out_link
		if user_signed_in? 
	 	  link_to('Logga ut', destroy_user_session_path, "data-toggle" => "true")
		end        
	end
end

app/helpers/design_helper.rb
module DesignHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/page_helper.rb
module PageHelper
  def opt_active(boolactive)

  end
end

app/helpers/system_helper.rb
module SystemHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/design/index.html.erb
<script src="http://static.jquery.com/ui/css/demo-docs-theme/ui.theme.css" type="text/css"></script>
<script src="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css"></script>

<style>
#sortable { list-style-type: none; margin: 0; padding: 0; }
	#sortable li { margin: 3px 3px 3px 0; padding: 1px; float: left; width: 262px; height: 262px; font-size: 4em; text-align: center; }
	#resizable { width: 120px; height: 120px; padding: 0.5em; position: relative;}
	#resizable h3 { text-align: center; margin: 0; }
	.ui-resizable-helper { border: 1px dotted gray; }
	</style>
<script>
	$(function() {
		var totalSize = 850;
		$("#layout_holder").hide();
		$( "#sortable" ).sortable();
		$( "#sortable" ).disableSelection();

		$( "#draggable" ).draggable({
			connectToSortable: "#sortable",
			helper: "clone",
			revert: "invalid"
		});
		$( ".ui-state-default" ).resizable({
			animate: true,
			maxWidth: totalSize,
			ghost: true,
			helper: 'ui-state-highlight',
			stop: function(event, ui) {console.log(ui);}
		});
		
		$(".create-layout").on("click", function(event){
			event.preventDefault();
			$("#layout_holder").fadeToggle("fast");
      		
     	});
	});
</script>
<div style="margin-left: 20px; width: 868px; margin-bottom: 15px;" class="subnav">
    <ul class="nav nav-pills">
      <li><a href="#typography">Skapa layout</a></li>
      <li><a href="#code">Dina layouter</a></li>
      <li><a href="#tables">....</a></li>
      <li><a href="#forms">...</a></li>
      <li><a href="#buttons">...</a></li>
    </ul>
  </div>
<div style="width: 819px;" class="alert alert-info span10">
<p>
  På Design kan du skapa nya unika layouter men också välja på våra klara. 
</p>
</div>


<div id="right_col" class="well span11">
  <h2>Layouter</h2>
 	<% if @layout.empty? %>
 		<div class="alert alert-warning">
 			<i class="icon-info-sign"></i>
 			Det finns inga layouter ännu.
 			Skapa en layout genom att trycka på knappen "Skapa layout"
 		</div>
 	<% else %>
	 	<% @layout.each do |layouts| %>
	 		<p><%= layouts.name %></p>
	 	<% end %>
 	<% end %>
 	<a href="" class="btn btn-large btn-success create-layout" data-toggle="true">Skapa en egen</a>
 	<a href="" class="btn btn-large btn-warning create-box" data-toggle="true">Skapa en box</a>
 

 	<div style="height: 500px;" id="layout_holder" class="alert alert-success">
    	<div class="demo">

			<ul id="sortable">
				<li class="ui-state-default"></li>
				<li class="ui-state-default"></li>
				<li class="ui-state-default"></li>	
			</ul>
		</div><!-- End demo -->
    </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="span3 offset3">
  <h3>Var god logga in</h3>
</div>
<div id="login" class="span5 offset3 well">
   <%= form_for("user", :url => user_session_path, :method => "post") do |f| %>
    <%= f.text_field :email, :placeholder => "Skriv in din email..."  %>
    <%= f.password_field :password %>
    <p>
      <%= f.submit 'Logga in', :class => "btn btn-success"%>
    </p>
   <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CMS</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "twitter/bootstrap/bootstrap-scrollspy.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "CMS-BUILDER", root_path, :class => "brand", style: "margin-left: -28px;" %>
      <ul class="nav">
      <% if user_signed_in? %>
         <li><%= link_to "Sidor", pages_path, :class => "popuper" %></li>
         <li><%= link_to "Design", design_index_path %></li>
         <li><%= link_to "Add-ons", "/info" %></li>
         <li><%= link_to "Användare", "/contact" %></li>
         <li><%= link_to "Verktyg", "/contact" %></li>
       <li id="uname" class="btn btn-info" data-content="information" rel="popover" data-original-title="Kundinformation"><b> <%= current_user.email %></b></li>
      <% else %>
         <li><%= link_to "Information", "/info" %></li>
         <li><%= link_to "Hjälp", "/contact" %></li>
      <% end %>
      </ul>
    </div>
  </div>
</div>
<div style="margin-top: 70px;" class="container">
  <div class="row">
  </div>
  <div id="content" class="row" data-pjax-container>
    <%= yield %>
  </div>
  <div class="row">
  </div>
</div>
</body>
</html>

app/views/pages/_pagetree.html.erb
<script>
$(document).ready(function() {
  $('.subpage').each(function(index) {
    $(".sortable."+$(this).attr("data-subid")).append("<li style='font-size: 9px; margin-left: 20px;' id="+$(this).attr("data-id")+" data-id="+$(this).attr("data-subid")+" style='margin-left: 23px;'><a style='color: black;' id="+$(this).attr("data-id")+" href='/pages/"+$(this).attr("data-id")+" class='page'>"+$(this).attr("data-name")+"</a></li>");
  });
});
</script>
<div class="span3">
  <div class="well" id="menu" style="padding: 8px 0;">
    <ul id="sortable" class="nav nav-list">
      <li class="nav-header">Sidträd</li>
     	<% @pageTree.each do |page| %>
      <ol class="rounded-list">
      <% if page.subpage == 0 %>
        <li data-id= <%= page.id %>  class="sortable <%= page.id %>" id=<%= page.sortable %>>
          <%= link_to content_tag("span", page.name, style: "min-width: 200px;"),page_path(page), id: "#{page.id}", "data-id" =>  "#{page.id}",  class: "label label-info" %>
        </li>
        <% else #Is subpage, hide and get data %>
          <div style="display: none;" class="subpage" data-name= <%=page.name %> data-id=<%= page.id %> data-subid=<%= page.subpage %>><%=page.name %></div>
       <% end %>
     		</ol>
     	<% end %>
      <li class="nav-header">Another list header</li>
      <li><a href="#"><i class="icon-user"></i> Konto</a></li>
      <li><a href="#"><i class="icon-cog"></i> Inställnngar</a></li>
      <li><a href="#"><i class="icon-flag"></i> Hjälp</a></li>
      <li><%= fetch_sign_out_link %></li>
    </ul>
  </div>
</div>

app/views/pages/index.html.erb
<%= render "pagetree" %>
<% if flash[:notice] %>
	<div class="span8">
    	<div id="notice" class="alert alert-danger well"><%= flash[:notice] %></div>
    </div>
    <% end %>
<div id="right_col" class="well span8">
  <h3>Huvudsidor</h3>
  	<table class="table table-striped table-bordered table-condensed">
    	<tr>
    		<th>Sidnamn</th>
    		<th>Publicerad</th>
        <th>Kan editeras</th>
    		<th>Senast ändrad</th>
        <th>Integrera</th>
    	</tr>
  		<% @pageTree.each do |pagetree| %>
        <% if pagetree.subpage == 0 %>
          <% if pagetree.activated == 1 then activated = link_to "Ja", "#", class: "btn btn-success disabled page_status" else activated =  link_to "Nej", "#", class: "btn btn-danger disabled page_status" end %>
          <% if pagetree.editable  == 1 then editable = link_to "Ja", "#", class: "btn btn-success disabled page_status" else editable  = link_to "Nej", "#", class: "btn btn-danger disabled page_status" end %>
    			<tr>
    				<td><%= pagetree.name %></td>
    				<td><%= activated %></td>
            <td><%= editable %></td>
    				<td><%= pagetree.updated_at %></td>
            <td style="text-align: center; padding-to<p: 8px;"><%= link_to "Besök sida", page_path(pagetree), class: "btn btn-info" %></td>
    			</tr>
        <% end %>
  		<% end %>
  	 </table>

     <h3>Undersidor</h3>
    <table class="table table-striped table-bordered table-condensed">
      <tr>
        <th>Sidnamn</th>
        <th>Publicerad</th>
        <th>Kan editeras</th>
        <th>Senast ändrad</th>
        <th>Integrera</th>
      </tr>
      <% @pageSubs.each do |pagetree| %>
        <% if pagetree.activated == 1 then activated = link_to "Ja", "#", class: "btn btn-success disabled page_status" else activated =  link_to "Nej", "#", class: "btn btn-danger disabled page_status" end %>
        <% if pagetree.editable  == 1 then editable = link_to "Ja", "#", class: "btn btn-success disabled page_status" else editable  = link_to "Nej", "#", class: "btn btn-danger disabled page_status" end %>
        <tr>
          <td><%= pagetree.name %></td>
          <td><%= activated %></td>
          <td><%= editable %></td>
          <td><%= pagetree.updated_at %></td>
          <td style="text-align: center; padding-to<p: 8px;"><%= link_to "Besök sida", page_path(pagetree), class: "btn btn-info" %></td>
        </tr>
      <% end %>
     </table>
</div>

app/views/pages/show.html.erb
<script>
$("#page-change").on("click", function(event){
  $("div.controls").removeClass("controlls");
  $("div.controls").addClass("control-group success");
  $(".input-xlarge").css("background", "#ABEBB4");
  setTimeout(function(){
      $("div.controls").removeClass("control-group success"); 
      $(".input-xlarge").css("background", "white");
  }, 1000);
});
 
$("#option-activate").on("click", function(event){
  $("div.controls").removeClass("controlls");
  $("div.controls").addClass("control-group success");
  $(".input-xlarge").css("background", "#ABEBB4");
  setTimeout(function(){
      $("div.controls").removeClass("control-group success"); 
      $(".input-xlarge").css("background", "white");
  }, 1000);
});

   $('.hidden').hide();
   $('#myModal').hide();
   $('#subpageModal').hide();
   $(".create-page").on("click", function(){
      $('.new_page').submit();
     });
  $(".delete-page").on("click", function(event){
    event.preventDefault();
    $(".delete-page").fadeOut("fast");
    $('.hidden').fadeIn("fast");
    
  });
  $('#editable_form').on("click", function(event){
      if($("#option-editable").attr("value") == 0)
      {
        $("#option-editable").attr("value", 1)
      }
      else
      {
        $("#option-editable").attr("value", 0)
      } 
  });
  setTimeout(function(){
      $('.enable').on("click", function(event){
      if($("#option-activate").attr("value") == 0)
      {
        $("#option-activate").attr("value", 1)
      }
      else if($("#option-activate").attr("value") == 1)
      {
        $("#option-activate").attr("value", 0)
      } 
  });
  }, 1000);
  $( "#sortable" ).sortable({
    receive: function(event, ui) { 
    
}
  });
  $( "#sortable" ).bind( "sortupdate", function(event, ui) {
    console.log($(ui.item.context.children).attr("id"))
  });
 $( "#sortable" ).disableSelection();
</script>
<div class="modal" id="myModal">
  <div class="modal-header">
  <a class="close" data-dismiss="modal">×</a>
  <h3>Skapa en ny sida</h3>
  </div>
  <div class="modal-body">
    <%= form_for Page.new, id: "create" do |form| %>
    <div class="control-group">
        <label class="control-label" for="siteName">Sidnamn</label>
        <div class="controls">
        <%= form.text_field :name, class: "input-xlarge focused", placeholder: "Lorem ipsum" %>
        </div>
    </div>
    <div class="controls">
      <label class="control-label" for="textarea">Standard text</label>
      <%= form.text_area(:content, style: "height: 200px; width: 350px;") %>
    </div>
    </div>
  
  <div class="modal-footer">
    <%= form.submit "Skapa sida", class: "btn btn-success btn-large create-page", "data-toggle" => "true" %>
    <a href="#" data-dismiss="modal" class="btn btn-large">Stäng detta fönster</a>
  </div>
  <% end %>
</div>
<div class="modal" id="subpageModal">
  <div class="modal-header">
  <a class="close" data-dismiss="modal">×</a>
  <h3>Skapa en ny undersida för <%= @page.name %></h3>
  </div>
  <div class="modal-body">
    <%= form_for Page.new, id: "create-sub" do |form| %>
    <div class="control-group">
        <label class="control-label" for="siteName">Sidnamn</label>
        <div class="controls">
          <%= form.text_field :name, class: "input-xlarge focused", placeholder: "Lorem ipsum" %>
        </div>
    </div>
    <div class="controls">
      <label class="control-label" for="textarea">Standard text</label>
      <%= form.text_area(:content, style: "height: 200px; width: 350px;") %>
    </div>
      <%= form.hidden_field :subpage, {:value => @page.id} %>
    </div>
  
  <div class="modal-footer">
    <%= form.submit "Skapa undersida", class: "btn btn-success btn-large create-page", "data-toggle" => "true" %>
    <a href="#" data-dismiss="modal" class="btn btn-large">Stäng detta fönster</a>
  </div>
  <% end %>
</div>
<div style="width: 819px;" class="alert alert-info span8">
	<b>Allämn information om denna sidan</b>
	<ul style="padding: 5px;">
		<li>Ändra sidinställningar</li>
		<li>Skapa nya sidor</li>
    <li>Ta bort sidor</li>
	</ul>
</div>
<div  class="row">
  <div style="margin-bottom: 8px; margin-top:-10px; margin-left: 578px; width: 350px;" class="span3 ">
    <%= link_to "Skapa en ny sida", "#myModal", 
                :class => "btn btn-success btn-large", 
                "data-toggle" => "modal" %>
    <% if @page.subpage == 0 %>
        <% create_sub_disabled = "" %>
      <% else %>
        <% create_sub_disabled = "disabled" %>
        <% destroy_modal       = "destroy" %>
    <% end %>
      <%= link_to "Skapa en ny undersida", "#subpageModal #{destroy_modal}", 
                :class => "btn btn-info btn-large #{create_sub_disabled}", 
                "data-toggle" => "modal" %>
    
  </div>
</div>

<%= render "pagetree" %>
<div id="right_col" class="well span8">
  <div class="span8 data-display">
<!--     <h3>Du editerar just nu sidan: <%= @page.name %></h3>
 -->    <div style="width: 555px;" class="alert alert-info">
      Tryck på önskad inställning för att aktivera eller inaktivera en inställning.
    </div>
    <div class="control-group" id="change">
      <label class="control-label" for="focusedInput">Sidnamn</label>
      <div class="controls">
      <%= form_for @page, remote: true do |form| %>
        <%= form.text_field :name, class: "input-xlarge focused", placeholder: @page.name %>
        <p>
          <%= form.submit "Ändra", class: "btn", id: "page-change", data: {toggle: "request"} %>
        </p>
      <% end %>
      </div>
    </div>
    <div id="settings">
    <%= form_for @page, remote: true do |form| %>
      <p>
        <p>Allmäna inställningar</p>
        <%= form.submit "Publicerad",
                        class: 
                          if @page.activated == 1 
                            then "btn btn-info btn-small active" 
                            else "btn btn-info btn-small" 
                          end, 
                          "data-toggle" => "button" %>
        <%= form.hidden_field :activated, id: "option-activate", 
                              value: 
                              if @page.activated == 1 
                                then 0 
                                else 1 
                              end
        %>
       <% end %>

       <%= form_for @page, remote: true, :'data-update-target' => "settings" do |form| %>
          <%= form.submit "Editerbar", 
                          class: 
                            if @page.editable == 1 
                              then "btn btn-info btn-small active enable" 
                              else "btn btn-info btn-small enable" 
                            end, 
                            "data-toggle" => "button" %>
          <%= form.hidden_field :editable, id: "option-editable", 
                              value: 
                              if @page.editable == 1 
                                then 0 
                                else 1 
                              end 
           %>
      <% end %>
      
      </p>
    </div>
  <p>
     <p>Modul inställningar</p>
      <a class="btn btn-info btn-small" data-toggle="button" href="#">
      <i class="icon-cog icon-white"></i>
          Lösenordsskyddad
    </a>
     <a class="btn btn-info btn-small" data-toggle="button" href="#">
      <i class="icon-cog icon-white"></i>
          Nyheter
    </a>
    <a class="btn btn-info btn-small" data-toggle="button" href="#">
      <i class="icon-cog icon-white"></i>
          Bildgalleri
    </a>
    </p>

    <div style="margin-left: 480px; margin-top: 5px;" class="span2">
        <%= link_to "Editera sida", "http://frontend.dev/editor/pages/" + @page.id.to_s, :class => "btn btn-warning", "style" => "width: 102px;", "target" => "_window" %>
    </div>
    <div style="margin-left: 480px; margin-top: 5px;" class="span2" id="removeHolder">
        <%= link_to "Ta bort sida", "#", "data-id" => "#{@page.id}",  class: "btn btn-danger delete-page", "style" => "width: 102px;", "data-toggle" => "request" %>
         <div class="hidden">
            <%= form_for @page, method: "delete" do |form| %>
            <%= link_to "Nej", "#", class: "btn btn-danger", style: "position: absolute; margin-top: 0px; height: 16px;" %>
            <%= form.submit "Acceptera", class: "btn btn-success", style: " margin-left:45px;"  %>
          <% end %>
        </div>
    </div>
   
  
</div>
  
</div>

app/views/pages/update.js.erb
$("li#<%=@page.id%> a").html("<%= j @page.name %>");

app/views/system/index.html.erb
<div style="width: 819px;" class="alert alert-info span10">
<p>
  Detta är din huvudsida, här ser du ett huvudflöde vad som hänt sen du senast loggade in.  
</p>
</div>
<div class="span3">
  <div class="well" style="padding: 8px 0;">
    <ul class="nav nav-list">
      <li class="nav-header">List header</li>
      <li class="active"><a href="#"><i class="icon-white icon-home"></i> Dashboard</a></li>
      <li><a href="#"><i class="icon-cog"></i> Verktyg</a></li>
      <li><a href="#"><i class="icon-pencil"></i> Applications</a></li>
      <li class="nav-header">Another list header</li>
      <li><a href="#"><i class="icon-user"></i> Konto</a></li>
      <li><a href="#"><i class="icon-cog"></i> Inställnngar</a></li>
      <li><a href="#"><i class="icon-flag"></i> Hjälp</a></li>
      <li><%= fetch_sign_out_link %></li>
    </ul>
  </div>
</div>
<div id="right_col" class="well span8">
  <h2>Dashboard</h2>
  <div class="span3 data-display">
    <p class="bold">Senaste inlaggda sidor</p>
    <%= @client_ip %>
  </div>
   <div class="span3 data-display">
    <p class="bold">Senaste inloggningar</p>
    <p>
      <%= @dashoard.fetch_last_sign_in(current_user) %>
    </p>
  </div>
</div>

app/views/system/pages.html.erb
<div class="modal" id="myModal">
  <div class="modal-header">
  <a class="close" data-dismiss="modal">×</a>
  <h3>Skapa en ny sida</h3>
  </div>
  <div class="modal-body">
    <div class="control-group">
        <label class="control-label" for="siteName">Sidnamn</label>
        <div class="controls">
        <input id="siteName" class="input-xlarge focused site-name" type="text" placeholder="Lorem ipsum"> 
        </div>
    </div>
    <div class="controls">
      <label class="control-label" for="textarea">Standard text</label>
      <textarea style="height: 230px; width: 400px;" rows="10" id="textarea" class="input-xlarge">
   Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin consequat sem nec diam rutrum a tempor dui lacinia. Nunc aliquet mattis eros sed interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur scelerisque quam ut mi mattis sed imperdiet metus dictum. Maecenas lorem nibh, ultricies eu congue at, sagittis in nunc.Praesent vitae velit vel purus posuere volutpat. Aenean non lorem neque. Nullam interdum est ut nunc convallis eu pulvinar diam rhoncus. 
      </textarea>
    </div>

    </div>
  <div class="modal-footer">
  <a href="#" data-toggle="request" class="btn btn-success btn-large create-page">Skapa sida</a>
  <a href="#" data-dismiss="modal" class="btn btn-large">Stäng detta fönster</a>
  </div>
</div>
<div style="width: 819px;" class="alert alert-info span10">
	<b>Allämn information om denna sidan</b>
	<ul>
		<li>Ändra sidinställningar</li>
		<li>Skapa nya sidor</li>
	</ul>
</div>
<div class="span3">
  <div class="well" style="padding: 8px 0;">
    <ul class="nav nav-list">
      <li class="nav-header">Sidträ</li>
     <ol class="trees">
     	<% @pageTree.each do |pt| %>
     		<li class="file">
     			<%= link_to "#{pt.name}", "/pages/#{pt.id}", :class => "getinfo icon-file", "data-id" =>  "#{pt.id}", remote: false %>
     		</li>
     	<% end %>

	 <!--    
	  <li>
	        <label for="subfolder1">Subfolder 1</label>
	        <input type="checkbox" id="subfolder1" />
	        <ol>
	            <li class="file"><a href="">File 2</a></li>
	            <li class="file"><a href="">File 2</a></li>
	            <li class="file"><a href="">File 2</a></li>
	        </ol>
	    </li>  -->
	 </ol>
      <li class="nav-header">Another list header</li>
      <li><a href="#"><i class="icon-user"></i> Konto</a></li>
      <li><a href="#"><i class="icon-cog"></i> Inställnngar</a></li>
      <li><a href="#"><i class="icon-flag"></i> Hjälp</a></li>
      <li><%= fetch_sign_out_link %></li>
    </ul>
  </div>
</div>

<div id="right_col" class="well span8">
  <div class="span8 data-display">
    <% @p_settings.each do |page| %>
    <div style="width: 555px;" class="alert alert-info">
      Tryck på önskad inställning för att aktivera eller inaktivera en inställning.
    </div>
    <div class="control-group">
      <label class="control-label" for="focusedInput">Sidnamn</label>
      <div class="controls">
      <input id="focusedInput" class="input-xlarge focused" type="text" placeholder=" <%= "#{page.name}" %>"> 
      <p><a data-id="<%= page.id %>" data-toggle="request" href="#" class="btn update-page">Ändra</a></p>
      </div>
    </div>
    <p>
    <p>Allmäna inställningar</p>
    <a class="btn btn-info btn-small" data-toggle="button" href="#">
      <i class="icon-cog icon-white"></i>
          Publicerad
    </a>
    <a class="btn btn-info btn-small" data-toggle="button" href="#">
      <i class="icon-cog icon-white"></i>
          Editerbar
    </a>
  </p>
  <p>
     <p>Modul inställningar</p>
      <a class="btn btn-info btn-small" data-toggle="button" href="#">
      <i class="icon-cog icon-white"></i>
          Lösenordsskyddad
    </a>
     <a class="btn btn-info btn-small" data-toggle="button" href="#">
      <i class="icon-cog icon-white"></i>
          Nyheter
    </a>
    <a class="btn btn-info btn-small" data-toggle="button" href="#">
      <i class="icon-cog icon-white"></i>
          Bildgalleri
    </a>
    </p>
    <div style="margin-left: 480px;" class="span2">
        <%= link_to "Skapa en ny sida", "#myModal", 
                    :class => "btn btn-success ", 
                    "data-toggle" => "modal" %>
    </div>
    <div style="margin-left: 480px; margin-top: 5px;" class="span2">
        <%= link_to "Editera sida", "http://frontend.dev/editor/pages/" + page.id.to_s, :class => "btn btn-warning", "style" => "width: 102px;", "target" => "_window" %>
    </div>
    <div style="margin-left: 480px; margin-top: 5px;" class="span2">
        <%= link_to "Ta bort sida", "#", "data-id" => "#{page.id}",  class: "btn btn-danger delete-page", "style" => "width: 102px;", "data-toggle" => "request" %>
    </div>
<% end %>
  
</div>
  
</div>